language: ruby
rvm:
- 2.3.3

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --url-ignore "#,/talks,/about" --only-4xx

branches:
  only:
  - backup
