# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael Herman
email: michael@mherman.org
author: Michael Herman
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mherman.org" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-37074204-1
sharing: true # via addthis
# disqus_short_name: michaelherman

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
destination: docs

permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

kramdown:
  toc_levels: 2..2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
