title: Michael Herman
email: michael@mherman.org
author: Michael Herman
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mherman.org" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-37074204-1
disqus_short_name: michaelherman
sharing: true # via addthis
comments: true # via disqus

markdown: kramdown
theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap

permalink: /blog/:year/:month/:day/:title/

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

kramdown:
  toc_levels: 2..2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
